"""empty message

Revision ID: 07fbe4f6fe48
Revises: a28093b6e425
Create Date: 2024-03-22 15:13:26.954929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07fbe4f6fe48'
down_revision: Union[str, None] = 'a28093b6e425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable='True')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
