"""empty message

Revision ID: a28093b6e425
Revises: 172d45fa0f26
Create Date: 2024-03-22 15:12:53.964096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a28093b6e425'
down_revision: Union[str, None] = '172d45fa0f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('type_of_post', sa.Integer(), nullable=False))
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable='True')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('posts', 'type_of_post')
    # ### end Alembic commands ###
