"""empty message

Revision ID: e19bb5a06a7f
Revises: 1a872ab2211d
Create Date: 2024-03-22 12:49:32.351832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e19bb5a06a7f'
down_revision: Union[str, None] = '1a872ab2211d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable='True')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'expire',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
